### ISSUE TITLE
Foyer: Refactor from_foyer to a classmethod of System

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-system#192]
It might be useful to move the free-floating function [`from_foyer`](https://github.com/openforcefield/openff-system/blob/e1a329d2cfcbfa3b64d5d8919ac8dcc69eed8715/openff/system/components/foyer.py#L67) into a classmethod (`System.from_foyer`). This should only necessitate moving that function; the other classes can stay put. See  #191 for some reasoning in the parallel case of SMIRNOFF typing.

cc: @umesh-timalsina @justinGilmer

**Comment by justinGilmer** [comment]
Working on this in the next day or two, can you assign me @mattwthompson

**Comment by mattwthompson** [comment]
Sure! Feel free to use refer to the current [`System.from_smirnoff`](https://github.com/openforcefield/openff-system/blob/27ded15f159f02e9c343c50c32093b06cd66edde/openff/system/components/system.py#L122) for inspiration as well
