### ISSUE TITLE
Purge stale branches

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-system#197]
# Description

The repo has a lot of stale branches open which I think are probably just leftover from merged PRs. It would be good to quickly go over them and delete any which are no longer needed:

![image](https://user-images.githubusercontent.com/22272126/118949472-2dfd5a00-b951-11eb-8347-8412a94f7768.png)

**Comment by mattwthompson** [comment]
Trimmed out the stale branches, down to 15 now. I grew up on the fork/PR model so cleaning up my mess isn't a habit of mine
