### ISSUE TITLE
Units: Prototype of typed array model

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-system#60]
This prototype is mostly a repackaging of others' work in a few different places (thanks @dgasmith and several in https://github.com/samuelcolvin/pydantic/issues/380. It serves as one way that array-like data can be stored with tagged units, constructed via reasonable attempts at processing imperfect inputs, and look reasonable to the user. Serialization is not yet implemented (aside from free `model.dict()` stuff, i.e. JSON doesn't work).

https://gist.github.com/mattwthompson/3a7d9959d20d7bbb10b06c894c5e5acc

Related #39

**Comment by mattwthompson** [comment]
Updated with a JSON encoder (no decoder): https://gist.github.com/mattwthompson/5a22cf9579f5083f02b1ccf734a1f7a7

**Comment by mattwthompson** [comment]
Took the encoder from here: https://github.com/MolSSI/QCElemental/blob/52c81715d0975a444d419f85e2e681323755f566/qcelemental/util/serialization.py#L119

**Comment by umesh-timalsina** [comment]
I took a shot at decoding, [here](https://gist.github.com/umesh-timalsina/fdff4688c442b698743d29a0a93a8893#file-array_typing-py). This approach works,  basically, you could define/decorate decoder at module/package level. Previously, I had tried an approach of overriding `parse_obj` method for `BaseModel`, which was painful for recursive Models. One catch here is that  a universal decoding pattern esp. with these nested `json` strings can be non-trivial, which I just encountered and had to pull some hack (is_pint: True) and had to decode over and over again (although a recursive approach to decode json string or may be some python magic is out there, which I might be missing).

**Comment by mattwthompson** [comment]
Another downside of this approach is that, for each physical data that has different dimensionality, a different subclass will need to be generated. Off the top of my head, each of these force field parameters has different dimensionality

* sigma
* epsilon
* bond k
* angle k
* angle theta
* partial charge
* torsion periodicity
* torsion force constant

Yet another missing detail is how to build the values of each of these off of some default registry somewhere, such that a user could provide a list of different `base_unit`s that are propagated out. See https://lammps.sandia.gov/doc/units.html

**Comment by dgasmith** [comment]
You can build a quantity array that takes a string type argument, ‘Quantity[“kcal/mol”]’.

**Comment by mattwthompson** [comment]
Is that at conflict with the design you presented that enables each class to default to a defined `base_type`?
